### ISSUE TITLE
Not finding missing messages in my application

### ISSUE THREAD

**Issue by colinmackinlay** [hexadog/laravel-translation-manager#1]
Hello, this looks like a great package. I've managed to get an `unused` report (it checks everything against the `hexadog` namespace as well as a blank namespace for my app).

What I can't get working is the `missing` report. I know I have missing messages but I just get this output:
```
1 missing translation found
+------+-----------+--------+
| Lang | Namespace | String |
+------+-----------+--------+
| en   |           |        |
+------+-----------+--------+
```
Can you suggest what might be going wrong?

Assuming I can get that working this seems like an excellent utility package. A feature request I'd have would be to have it check a single language file at a time if passed as a parameter. I have quite a few files to organise the messages for my app and it would be good to just check one at a time :)

**Comment by gaetan-hexadog** [comment]
Hi,

thanks for your feedback.
Unfortunately I can't reproduce your issue. Either `php artisan translation:unused` and `php artisan translation:missing` commands are working and give me results.
Maybe you could share a project with the issue so I'll take a look ?


I like the idea to be able to specify a language file to process as a parameter. I'll work on it.

**Comment by colinmackinlay** [comment]
Thanks for getting back to me. I've tested in a brand new Laravel app where I've added a `test.php` language file:
```
<?php

return [
    'used'   => 'This translation is used',
    'unused' => 'This translation is unused',
];
```
The welcome page has been amended to include this:
```
                                    {{__('test.used')}}
                                    {{__('test.missing')}}
```
If I use `php artisan translation:missing` I still get this:
```
1 missing translation found
+------+-----------+--------+
| Lang | Namespace | String |
+------+-----------+--------+
| en   |           |        |
+------+-----------+--------+

```
If I use `php artisan translation:unused` then I get everything as if it was in the hexadog namespace and then all over again in no namespace. Here's two extracts:
```
| en   | hexadog   | test.used                                  | This translation is used                                                   |
| en   | hexadog   | test.unused                                | This translation is unused                                                 |
```
and
```
| en   | hexadog   | validation.uuid                            | The :attribute must be a valid UUID.                                       |
| en   | hexadog   | validation.custom.attribute-name.rule-name | custom-message                                                             |
| en   |           | auth.failed                                | These credentials do not match our records.                                |
| en   |           | auth.password                              | The provided password is incorrect.                                        |
| en   |           | auth.throttle                              | Too many login attempts. Please try again in :seconds seconds.             |
| en   |           | pagination.previous                        | &laquo; Previous                                                           |
| en   |           | pagination.next                            | Next &raquo;                                                               |
| en   |           | passwords.reset                            | Your password has been reset!                                              |
| en   |           | passwords.sent                             | We have emailed your password reset link!                                  |
| en   |           | passwords.throttled                        | Please wait before retrying.                                               |
| en   |           | passwords.token                            | This password reset token is invalid.                                      |
| en   |           | passwords.user                             | We can't find a user with that email address.                              |
| en   |           | test.unused                                | This translation is unused                                                 |
| en   |           | validation.accepted                        | The :attribute must be accepted.                                           |
```
so I get unused correctly identified in my (blank) namespace but everything checked against the hexadog namespace which of course shows it all up as missing.

Perhaps the missing command isn't working because my namespace is blank? Not quite sure how I would put a namespace into my language files.

**Comment by gaetan-hexadog** [comment]
Please let me know if it's working correctly for you wiht the version 0.3.2

**Comment by colinmackinlay** [comment]
Perfect - both issues now resolved, thank you! Glad you liked the idea of adding a filter to which files to check - look forward to seeing that eventually. 

Another thought would be to be able to ignore some files in the unused check, perhaps through the config file? I won't edit the Laravel provided files down in case I want those messages in future but they add to the noise when checking.
